spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Northwind?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: sammy
    password: Lqsym2525!@
